# The main config file for your Jekyll template

# Site settings
title: Basudeb Dasgupta               # used for the html title of every page
desc: >
  Awesome description for Basudeb Dasgupta's new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: https://basudasgupta.github.io      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: bdasgupta@theory.tifr.res.in
author: basu
# twitter_username: bdasgupta
# github_username: basudasgupta
# github_source: basudasgupta.github.io

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Research
    url: /research/
    desc: work
  - title: Teaching
    url: /teaching/
    desc: more work
  - title: About
    url: /about/
    desc: bio

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

